### PR TITLE
session 1 solutions

### PR DESCRIPTION
**Pull request by HexTree**

### CODE REVIEW

**Comment by hadjimy** [comment]
I don't think is necessary to make a new notebook. Could you please instead update the current session1 notebook by running all cells, so that all output is visible? Also please add the relevant solution scripts in a /solutions/session1 folder.

**Comment by HexTree** [comment]
Ok, shall I just upload it under the original name. I didn't do it using scripts, should I?

**Comment by hadjimy** [comment]
Yes, I think is better to use the scripts I sent and use the %load command to load them.
It seems that there are some conflicts with the PR. Could you please first pull before you do any changes and resolve them?

**Comment by hadjimy** [comment]
Please use the same name otherwise the link in the web-page won't work.
So first make sure that you have an updated remote and then do the changes.

**Pull request closed without merging**
